name: Github Pages Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./
        run: npm install && npm run build:prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          folder: dist
